version: 2.1

orbs:
   heroku: circleci/heroku@1.2.6 # Invoke the Heroku orb

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference    
      - image: cimg/python:3.10.2
        steps:
          - checkout
          - run: python --version    
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: yarn install
      - run: yarn test

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: revive